//! IDEOCODE Daily Challenge (S5)
//!
//! Optional daily coding challenge generated by AI.
//! Solve it, earn points, climb the leaderboard.

use crate::tui::color_support::rgb;
use ideocode_tui_style::theme::*;
use ratatui::prelude::*;
use ratatui::text::Line;
use std::time::{SystemTime, UNIX_EPOCH};

#[derive(Debug, Clone)]
pub struct DailyChallenge {
    pub date: String,
    pub title: String,
    pub description: String,
    pub difficulty: ChallengeDifficulty,
    pub points: u32,
    pub solved: bool,
}

#[derive(Debug, Clone, PartialEq)]
pub enum ChallengeDifficulty {
    Easy,
    Medium,
    Hard,
    Expert,
}

impl ChallengeDifficulty {
    pub fn label(&self) -> &str {
        match self {
            ChallengeDifficulty::Easy => "Easy",
            ChallengeDifficulty::Medium => "Medium",
            ChallengeDifficulty::Hard => "Hard",
            ChallengeDifficulty::Expert => "Expert",
        }
    }

    pub fn color(&self) -> Color {
        match self {
            ChallengeDifficulty::Easy => neon_green(),
            ChallengeDifficulty::Medium => neon_yellow(),
            ChallengeDifficulty::Hard => neon_orange(),
            ChallengeDifficulty::Expert => rgb(255, 80, 80),
        }
    }

    pub fn points(&self) -> u32 {
        match self {
            ChallengeDifficulty::Easy => 10,
            ChallengeDifficulty::Medium => 25,
            ChallengeDifficulty::Hard => 50,
            ChallengeDifficulty::Expert => 100,
        }
    }
}

/// Get today's date as a string.
pub fn today_date() -> String {
    let Ok(now) = SystemTime::now().duration_since(UNIX_EPOCH) else {
        return "Unknown".to_string();
    };
    let days = now.as_secs() / 86400;
    format!("Day {}", days)
}

/// Generate a sample daily challenge.
pub fn get_daily_challenge() -> DailyChallenge {
    let date = today_date();
    DailyChallenge {
        date: date.clone(),
        title: "Reverse a String".to_string(),
        description: "Write a function that reverses a string without using built-in reverse methods.".to_string(),
        difficulty: ChallengeDifficulty::Easy,
        points: ChallengeDifficulty::Easy.points(),
        solved: false,
    }
}

/// Render daily challenge card.
pub fn render_daily_challenge(challenge: &DailyChallenge) -> Vec<Line<'static>> {
    let color = challenge.difficulty.color();

    vec![
        Line::from(Span::styled(
            "📅 Daily Challenge",
            Style::default()
                .fg(neon_cyan())
                .add_modifier(Modifier::BOLD),
        )),
        Line::from(Span::styled(
            format!("   {}", challenge.date),
            Style::default().fg(dim_color()),
        )),
        Line::from(""),
        Line::from(Span::styled(
            format!("   {}", challenge.title),
            Style::default()
                .fg(color)
                .add_modifier(Modifier::BOLD),
        )),
        Line::from(Span::styled(
            format!("   {}", challenge.description),
            Style::default().fg(dim_color()),
        )),
        Line::from(""),
        Line::from(vec![
            Span::styled(
                format!("   {} ", challenge.difficulty.label()),
                Style::default().fg(color),
            ),
            Span::styled(
                format!("• {} points", challenge.points),
                Style::default().fg(neon_yellow()),
            ),
            Span::styled(
                if challenge.solved { " • ✅ Solved" } else { "" },
                Style::default().fg(neon_green()),
            ),
        ]),
    ]
}

/// Render challenge leaderboard.
pub fn render_challenge_leaderboard() -> Vec<Line<'static>> {
    vec![
        Line::from(Span::styled(
            "🏆 Challenge Leaderboard",
            Style::default()
                .fg(neon_yellow())
                .add_modifier(Modifier::BOLD),
        )),
        Line::from(""),
        Line::from(vec![
            Span::styled(" 1. ", Style::default().fg(neon_yellow())),
            Span::styled("Alice", Style::default().fg(neon_cyan())),
            Span::styled(" - 2,450 pts", Style::default().fg(dim_color())),
        ]),
        Line::from(vec![
            Span::styled(" 2. ", Style::default().fg(neon_cyan())),
            Span::styled("Bob", Style::default().fg(neon_cyan())),
            Span::styled(" - 2,100 pts", Style::default().fg(dim_color())),
        ]),
        Line::from(vec![
            Span::styled(" 3. ", Style::default().fg(neon_orange())),
            Span::styled("Charlie", Style::default().fg(neon_cyan())),
            Span::styled(" - 1,850 pts", Style::default().fg(dim_color())),
        ]),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn daily_challenge_creation() {
        let challenge = get_daily_challenge();
        assert!(!challenge.title.is_empty());
    }

    #[test]
    fn difficulty_points() {
        assert_eq!(ChallengeDifficulty::Easy.points(), 10);
        assert_eq!(ChallengeDifficulty::Expert.points(), 100);
    }
}
