//! IDEOCODE Daily Challenge (S5)
//!
//! Optional daily coding challenge generated by AI.
//! Solve it, earn points, climb the leaderboard.

use crate::tui::color_support::rgb;
use ideocode_tui_style::theme::*;
use ratatui::prelude::*;
use ratatui::text::Line;
use std::time::{SystemTime, UNIX_EPOCH};

#[derive(Debug, Clone)]
pub struct DailyChallenge {
    pub date: String,
    pub title: String,
    pub description: String,
    pub difficulty: ChallengeDifficulty,
    pub points: u32,
    pub solved: bool,
}

#[derive(Debug, Clone, PartialEq)]
pub enum ChallengeDifficulty {
    Easy,
    Medium,
    Hard,
    Expert,
}

impl ChallengeDifficulty {
    pub fn label(&self) -> &str {
        match self {
            ChallengeDifficulty::Easy => "Easy",
            ChallengeDifficulty::Medium => "Medium",
            ChallengeDifficulty::Hard => "Hard",
            ChallengeDifficulty::Expert => "Expert",
        }
    }

    pub fn color(&self) -> Color {
        match self {
            ChallengeDifficulty::Easy => neon_green(),
            ChallengeDifficulty::Medium => neon_yellow(),
            ChallengeDifficulty::Hard => neon_orange(),
            ChallengeDifficulty::Expert => rgb(255, 80, 80),
        }
    }

    pub fn points(&self) -> u32 {
        match self {
            ChallengeDifficulty::Easy => 10,
            ChallengeDifficulty::Medium => 25,
            ChallengeDifficulty::Hard => 50,
            ChallengeDifficulty::Expert => 100,
        }
    }
}

/// Get today's date as a string.
pub fn today_date() -> String {
    let Ok(now) = SystemTime::now().duration_since(UNIX_EPOCH) else {
        return "Unknown".to_string();
    };
    let days = now.as_secs() / 86400;
    format!("Day {}", days)
}

/// Generate a sample daily challenge.
pub fn get_daily_challenge() -> DailyChallenge {
    let date = today_date();
    let day_seed = date.chars().map(|c| c as u64).fold(0u64, |a, b| a.wrapping_add(b));
    let challenges = all_challenges();
    let idx = (day_seed as usize) % challenges.len();
    let (title, description, difficulty) = challenges[idx].clone();
    let points = difficulty.points();
    DailyChallenge {
        date,
        title: title.to_string(),
        description: description.to_string(),
        difficulty,
        points,
        solved: false,
    }
}

fn all_challenges() -> Vec<(&'static str, &'static str, ChallengeDifficulty)> {
    vec![
        ("Reverse a String", "Write a function that reverses a string without using built-in reverse methods.", ChallengeDifficulty::Easy),
        ("FizzBuzz Plus", "FizzBuzz for multiples of 3, 5, and 7. Handle negative numbers too.", ChallengeDifficulty::Easy),
        ("Palindrome Check", "Check if a string is a palindrome, ignoring spaces and punctuation.", ChallengeDifficulty::Easy),
        ("Find the Duplicates", "Given a sorted array, find all duplicates in O(n) time.", ChallengeDifficulty::Medium),
        ("Binary Search", "Implement binary search on a rotated sorted array.", ChallengeDifficulty::Medium),
        ("Merge Intervals", "Merge all overlapping intervals in a list of [start, end] pairs.", ChallengeDifficulty::Medium),
        ("LRU Cache", "Design and implement a Least Recently Used (LRU) cache.", ChallengeDifficulty::Hard),
        ("Tree Traversal", "Implement level-order, in-order, pre-order, and post-order traversal.", ChallengeDifficulty::Hard),
        ("Rate Limiter", "Design a token bucket rate limiter with burst support.", ChallengeDifficulty::Hard),
        ("Regex Engine", "Build a simplified regex engine supporting . and * metacharacters.", ChallengeDifficulty::Expert),
        ("Concurrent MapReduce", "Implement a MapReduce framework in Rust with thread pools.", ChallengeDifficulty::Expert),
        ("Interpreter", "Write a simple interpreter for a Lisp-like language.", ChallengeDifficulty::Expert),
        ("Sort Colors", "Sort an array with only 3 distinct values in a single pass.", ChallengeDifficulty::Easy),
        ("Valid Parentheses", "Check if a string of brackets is valid. Support [], (), {}.", ChallengeDifficulty::Easy),
        ("Matrix Rotation", "Rotate an NxN matrix 90 degrees in-place.", ChallengeDifficulty::Medium),
        ("Longest Substring", "Find the longest substring without repeating characters.", ChallengeDifficulty::Medium),
        ("Word Break", "Determine if a string can be segmented into dictionary words.", ChallengeDifficulty::Hard),
        ("Trie Implementation", "Implement a Trie with insert, search, and startsWith operations.", ChallengeDifficulty::Hard),
        ("Stream Dedup", "Remove duplicates from a stream of data with O(1) memory.", ChallengeDifficulty::Expert),
        ("SQL Parser", "Build a minimal SQL parser that handles SELECT, WHERE, and JOIN.", ChallengeDifficulty::Expert),
    ]
}

/// Render daily challenge card.
pub fn render_daily_challenge(challenge: &DailyChallenge) -> Vec<Line<'static>> {
    let color = challenge.difficulty.color();

    vec![
        Line::from(Span::styled(
            "📅 Daily Challenge",
            Style::default()
                .fg(neon_cyan())
                .add_modifier(Modifier::BOLD),
        )),
        Line::from(Span::styled(
            format!("   {}", challenge.date),
            Style::default().fg(dim_color()),
        )),
        Line::from(""),
        Line::from(Span::styled(
            format!("   {}", challenge.title),
            Style::default()
                .fg(color)
                .add_modifier(Modifier::BOLD),
        )),
        Line::from(Span::styled(
            format!("   {}", challenge.description),
            Style::default().fg(dim_color()),
        )),
        Line::from(""),
        Line::from(vec![
            Span::styled(
                format!("   {} ", challenge.difficulty.label()),
                Style::default().fg(color),
            ),
            Span::styled(
                format!("• {} points", challenge.points),
                Style::default().fg(neon_yellow()),
            ),
            Span::styled(
                if challenge.solved { " • ✅ Solved" } else { "" },
                Style::default().fg(neon_green()),
            ),
        ]),
    ]
}

/// Render challenge leaderboard.
pub fn render_challenge_leaderboard() -> Vec<Line<'static>> {
    vec![
        Line::from(Span::styled(
            "🏆 Challenge Leaderboard",
            Style::default()
                .fg(neon_yellow())
                .add_modifier(Modifier::BOLD),
        )),
        Line::from(""),
        Line::from(vec![
            Span::styled(" 1. ", Style::default().fg(neon_yellow())),
            Span::styled("Alice", Style::default().fg(neon_cyan())),
            Span::styled(" - 2,450 pts", Style::default().fg(dim_color())),
        ]),
        Line::from(vec![
            Span::styled(" 2. ", Style::default().fg(neon_cyan())),
            Span::styled("Bob", Style::default().fg(neon_cyan())),
            Span::styled(" - 2,100 pts", Style::default().fg(dim_color())),
        ]),
        Line::from(vec![
            Span::styled(" 3. ", Style::default().fg(neon_orange())),
            Span::styled("Charlie", Style::default().fg(neon_cyan())),
            Span::styled(" - 1,850 pts", Style::default().fg(dim_color())),
        ]),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn daily_challenge_creation() {
        let challenge = get_daily_challenge();
        assert!(!challenge.title.is_empty());
    }

    #[test]
    fn difficulty_points() {
        assert_eq!(ChallengeDifficulty::Easy.points(), 10);
        assert_eq!(ChallengeDifficulty::Expert.points(), 100);
    }
}
