[package]
name = "ideocode-provider-openrouter"
version = "0.1.0"
license = "MIT"
edition = "2024"

[dependencies]
dirs = "5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
bytes = "1"
futures = "0.3"
ideocode-core = { path = "../ideocode-core" }
ideocode-logging = { path = "../ideocode-logging" }
ideocode-message-types = { path = "../ideocode-message-types" }
reqwest = { version = "0.12", default-features = false, features = ["stream"] }
