import { useMemo } from "react";
import { LayoutTemplate, FileEdit, Check, X, File, FileText, GitCompare } from "lucide-react";
import { useFileStore } from "../../stores/fileStore";
import { IconButton } from "../ui/IconButton";

function formatBytes(bytes: number): string {
  if (bytes === 0) return "0 B";
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function getFileName(path: string): string {
  return path.split(/[/\\]/).pop() ?? path;
}

function getFileExtension(path: string): string {
  const name = getFileName(path);
  const dot = name.lastIndexOf(".");
  return dot > 0 ? name.slice(dot + 1) : "";
}

export function ComposerPanel() {
  const openFiles = useFileStore((s) => s.openFiles);
  const contents = useFileStore((s) => s.contents);
  const dirty = useFileStore((s) => s.dirty);
  const closeFile = useFileStore((s) => s.closeFile);
  const saveFile = useFileStore((s) => s.saveFile);
  const fileStats = useMemo(() => {
    const totalSize = openFiles.reduce((acc, f) => {
      const content = contents[f];
      return acc + (content ? new Blob([content]).size : 0);
    }, 0);
    const dirtyCount = openFiles.filter((f) => dirty[f]).length;
    return { total: openFiles.length, dirtyCount, totalSize };
  }, [openFiles, contents, dirty]);

  const dirtyFiles = useMemo(
    () => openFiles.filter((f) => dirty[f]),
    [openFiles, dirty],
  );

  const handleAcceptAll = async () => {
    for (const f of openFiles) {
      if (dirty[f]) {
        await saveFile(f, { silent: true });
      }
    }
  };

  const handleDiscardAll = () => {
    for (const f of openFiles) {
      if (dirty[f]) {
        closeFile(f);
      }
    }
  };

  const handleOpenInEditor = (path: string) => {
    useFileStore.getState().openFile(path);
  };

  if (openFiles.length === 0) {
    return (
      <div className="flex flex-col h-full bg-bg-primary" role="region" aria-label="Composer">
        <div className="p-3 border-b border-border-subtle bg-bg-secondary/50 flex flex-col gap-2">
          <h3 className="text-[13px] font-medium text-text-primary flex items-center gap-2">
            <LayoutTemplate size={14} className="text-accent-primary" />
            Composer
          </h3>
          <p className="text-[11px] text-text-muted">
            Review multi-file edits generated by Baanzon Verso.
          </p>
        </div>
        <div className="flex-1 flex flex-col items-center justify-center gap-3 px-4">
          <GitCompare size={32} className="text-text-muted/40" />
          <p className="text-[12px] text-text-muted text-center">
            No open files to review.
          </p>
          <p className="text-[11px] text-text-muted text-center">
            Open files or ask the assistant to generate edits.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full bg-bg-primary" role="region" aria-label="Composer">
      <div className="p-3 border-b border-border-subtle bg-bg-secondary/50 flex flex-col gap-2">
        <h3 className="text-[13px] font-medium text-text-primary flex items-center gap-2">
          <LayoutTemplate size={14} className="text-accent-primary" />
          Composer
        </h3>
        <p className="text-[11px] text-text-muted">
          Review multi-file edits generated by Baanzon Verso.
        </p>
        <div className="flex items-center gap-3 text-[10px] text-text-muted">
          <span className="flex items-center gap-1">
            <File size={10} />
            {fileStats.total} {fileStats.total === 1 ? "file" : "files"}
          </span>
          <span className="flex items-center gap-1">
            <FileText size={10} />
            {formatBytes(fileStats.totalSize)}
          </span>
          {fileStats.dirtyCount > 0 && (
            <span className="flex items-center gap-1 text-warning">
              <FileEdit size={10} />
              {fileStats.dirtyCount} modified
            </span>
          )}
        </div>
      </div>

      <div className="flex-1 overflow-y-auto p-2 space-y-1.5">
        {openFiles.map((filePath) => {
          const isDirty = !!dirty[filePath];
          const content = contents[filePath] ?? "";
          const lineCount = content ? content.split("\n").length : 0;
          const ext = getFileExtension(filePath);

          return (
            <div
              key={filePath}
              className={`flex flex-col border rounded-md overflow-hidden transition-colors ${
                isDirty
                  ? "border-warning/30 bg-bg-secondary/30"
                  : "border-border-subtle"
              }`}
            >
              <div className="flex items-center justify-between p-2 bg-bg-secondary border-b border-border-subtle">
                <button
                  onClick={() => handleOpenInEditor(filePath)}
                  className="flex items-center gap-2 text-[12px] font-medium text-text-primary hover:text-accent-primary transition-colors cursor-pointer text-left min-w-0"
                >
                  <FileEdit size={12} className="text-text-muted shrink-0" />
                  <span className="truncate">{getFileName(filePath)}</span>
                  {isDirty && (
                    <span className="w-1.5 h-1.5 rounded-full bg-warning shrink-0" />
                  )}
                </button>
                <div className="flex items-center gap-1 shrink-0">
                  {isDirty && (
                    <>
                      <IconButton
                        size="sm"
                        onClick={() => saveFile(filePath)}
                        className="text-success hover:bg-success/20"
                        label="Save file"
                      >
                        <Check size={14} />
                      </IconButton>
                      <IconButton
                        size="sm"
                        onClick={() => closeFile(filePath)}
                        className="text-error hover:bg-error/20"
                        label="Discard and close"
                      >
                        <X size={14} />
                      </IconButton>
                    </>
                  )}
                </div>
              </div>
              <div className="px-2 py-1.5 text-[10px] text-text-muted flex items-center gap-3 bg-bg-primary/50">
                <span className="font-mono truncate">{filePath}</span>
                <span className="shrink-0">
                  {lineCount} {lineCount === 1 ? "line" : "lines"}
                </span>
                {ext && (
                  <span className="shrink-0 uppercase font-medium text-text-muted">
                    {ext}
                  </span>
                )}
              </div>
            </div>
          );
        })}
      </div>

      {dirtyFiles.length > 0 && (
        <div className="p-3 border-t border-border-subtle bg-bg-secondary/80 flex gap-2">
          <button
            className="flex-1 py-1.5 px-3 bg-accent-primary text-white text-[12px] rounded hover:bg-accent-hover transition-colors font-medium flex items-center justify-center gap-1"
            onClick={handleAcceptAll}
          >
            <Check size={14} /> Accept All ({dirtyFiles.length})
          </button>
          <button
            className="flex-1 py-1.5 px-3 border border-border-strong text-text-primary text-[12px] rounded hover:bg-bg-tertiary transition-colors flex items-center justify-center gap-1"
            onClick={handleDiscardAll}
          >
            <X size={14} /> Discard All
          </button>
        </div>
      )}
    </div>
  );
}
