import { useState } from "react";
import { Check, X, FileEdit, LayoutTemplate } from "lucide-react";
import { IconButton } from "../ui/IconButton";

export function ComposerPanel() {
  const [diffs, setDiffs] = useState<{file: string, status: "pending" | "accepted" | "rejected"}[]>([
    { file: "src/App.tsx", status: "pending" },
    { file: "src/components/layout/Sidebar.tsx", status: "pending" }
  ]);

  const acceptDiff = (index: number) => {
    const next = [...diffs];
    next[index].status = "accepted";
    setDiffs(next);
  };

  const rejectDiff = (index: number) => {
    const next = [...diffs];
    next[index].status = "rejected";
    setDiffs(next);
  };

  const pendingCount = diffs.filter(d => d.status === "pending").length;

  return (
    <div className="flex flex-col h-full bg-bg-primary">
      <div className="p-3 border-b border-border-subtle bg-bg-secondary/50 flex flex-col gap-2">
        <h3 className="text-[13px] font-medium text-text-primary flex items-center gap-2">
          <LayoutTemplate size={14} className="text-accent-primary" />
          Composer
        </h3>
        <p className="text-[11px] text-text-muted">
          Review multi-file edits generated by Baanzon Verso.
        </p>
      </div>

      <div className="flex-1 overflow-y-auto p-2 space-y-2">
        {diffs.map((diff, i) => (
          <div key={i} className={`flex flex-col border rounded-md overflow-hidden ${diff.status === "pending" ? "border-border-subtle" : diff.status === "accepted" ? "border-success/30 opacity-70" : "border-error/30 opacity-50"}`}>
            <div className="flex items-center justify-between p-2 bg-bg-secondary border-b border-border-subtle">
              <span className="text-[12px] font-medium text-text-primary flex items-center gap-2">
                <FileEdit size={12} className="text-text-muted" />
                {diff.file}
              </span>
              {diff.status === "pending" && (
                <div className="flex items-center gap-1">
                  <IconButton size="sm" onClick={() => acceptDiff(i)} className="text-success hover:bg-success/20" label="Accept diff">
                    <Check size={14} />
                  </IconButton>
                  <IconButton size="sm" onClick={() => rejectDiff(i)} className="text-error hover:bg-error/20" label="Reject diff">
                    <X size={14} />
                  </IconButton>
                </div>
              )}
              {diff.status !== "pending" && (
                <span className="text-[10px] uppercase font-bold text-text-muted px-2">
                  {diff.status}
                </span>
              )}
            </div>
            {/* Fake Diff View */}
            <div className="p-2 bg-bg-primary font-mono text-[11px] overflow-x-auto whitespace-pre">
              <div className="text-error/80">- const oldVersion = true;</div>
              <div className="text-success/80">+ const newVersion = true;</div>
              <div className="text-text-muted">  console.log("Ready");</div>
            </div>
          </div>
        ))}
      </div>

      {pendingCount > 0 && (
        <div className="p-3 border-t border-border-subtle bg-bg-secondary/80 flex gap-2">
          <button 
            className="flex-1 py-1.5 px-3 bg-accent-primary text-white text-[12px] rounded hover:bg-accent-hover transition-colors font-medium flex items-center justify-center gap-1"
            onClick={() => {
              setDiffs(diffs.map(d => ({...d, status: d.status === "pending" ? "accepted" : d.status})));
            }}
          >
            <Check size={14} /> Accept All ({pendingCount})
          </button>
          <button 
            className="flex-1 py-1.5 px-3 border border-border-strong text-text-primary text-[12px] rounded hover:bg-bg-tertiary transition-colors flex items-center justify-center gap-1"
            onClick={() => {
              setDiffs(diffs.map(d => ({...d, status: d.status === "pending" ? "rejected" : d.status})));
            }}
          >
            <X size={14} /> Reject All
          </button>
        </div>
      )}
    </div>
  );
}
