//! First-run configuration for the local Baanzon Verso engine.
//!
//! Writes a minimal, engine-safe `.env` (only variables the engine is known to
//! respect) into the vendored gateway directory on first run. The zero-auth
//! fallback pool and cascade behavior are handled by the engine itself, not by
//! invented configuration keys.

use anyhow::{Context, Result};
use std::fs;
use std::path::PathBuf;

use crate::daemon::OMNIROUTE_PORT;

pub struct BaanzonConfig {
    gateway_dir: PathBuf,
}

impl BaanzonConfig {
    pub fn new(data_root: PathBuf) -> Self {
        Self {
            gateway_dir: data_root.join("baanzon-verso"),
        }
    }

    /// Writes the first-run environment file. Best effort: a failure to write
    /// is reported but never fatal (the engine runs fine from process env).
    pub fn generate_env(&self) -> Result<()> {
        fs::create_dir_all(&self.gateway_dir).context("failed to create gateway directory")?;

        let env_path = self.gateway_dir.join(".env");
        let env_content = format!(
            "# Auto-generated by IDEOCODE Baanzon Verso Configurator\n\
             OMNIROUTE_PORT={port}\n\
             OMNIROUTE_TELEMETRY=false\n\
             OMNIROUTE_LOG_LEVEL=error\n\
             OMNIROUTE_NO_UPDATE_NOTIFIER=1\n\
             OMNIROUTE_HIDE_HEALTHCHECK_LOGS=1\n",
            port = OMNIROUTE_PORT
        );

        fs::write(&env_path, env_content).context("failed to write Baanzon Verso .env file")
    }
}
